// Generated by gencpp from file readgps/Pose.msg
// DO NOT EDIT!


#ifndef READGPS_MESSAGE_POSE_H
#define READGPS_MESSAGE_POSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include "modules/localization/msf/include/PointENU.h"
#include "modules/localization/msf/include/Quaternion.h"
#include "modules/localization/msf/include/Point3D.h"

namespace readgps
{
template <class ContainerAllocator>
struct Pose_
{
  typedef Pose_<ContainerAllocator> Type;

  Pose_()
    : position()
    , orientation()
    , linear_velocity()
    , linear_acceleration()
    , angular_velocity()
    , heading(0.0)
    , linear_acceleration_vrf()
    , angular_velocity_vrf()
    , euler_angles()  {
    }
  Pose_(const ContainerAllocator& _alloc)
    : position(_alloc)
    , orientation(_alloc)
    , linear_velocity(_alloc)
    , linear_acceleration(_alloc)
    , angular_velocity(_alloc)
    , heading(0.0)
    , linear_acceleration_vrf(_alloc)
    , angular_velocity_vrf(_alloc)
    , euler_angles(_alloc)  {
  (void)_alloc;
    }



   typedef  ::readgps::PointENU_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef  ::readgps::Quaternion_<ContainerAllocator>  _orientation_type;
  _orientation_type orientation;

   typedef  ::readgps::Point3D_<ContainerAllocator>  _linear_velocity_type;
  _linear_velocity_type linear_velocity;

   typedef  ::readgps::Point3D_<ContainerAllocator>  _linear_acceleration_type;
  _linear_acceleration_type linear_acceleration;

   typedef  ::readgps::Point3D_<ContainerAllocator>  _angular_velocity_type;
  _angular_velocity_type angular_velocity;

   typedef double _heading_type;
  _heading_type heading;

   typedef  ::readgps::Point3D_<ContainerAllocator>  _linear_acceleration_vrf_type;
  _linear_acceleration_vrf_type linear_acceleration_vrf;

   typedef  ::readgps::Point3D_<ContainerAllocator>  _angular_velocity_vrf_type;
  _angular_velocity_vrf_type angular_velocity_vrf;

   typedef  ::readgps::Point3D_<ContainerAllocator>  _euler_angles_type;
  _euler_angles_type euler_angles;





  typedef boost::shared_ptr< ::readgps::Pose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::readgps::Pose_<ContainerAllocator> const> ConstPtr;

}; // struct Pose_

typedef ::readgps::Pose_<std::allocator<void> > Pose;

typedef boost::shared_ptr< ::readgps::Pose > PosePtr;
typedef boost::shared_ptr< ::readgps::Pose const> PoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::readgps::Pose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::readgps::Pose_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace readgps

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'readgps': ['/home/ubuwgb/catkin_ws/src/readgps/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::readgps::Pose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::readgps::Pose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::readgps::Pose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::readgps::Pose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::readgps::Pose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::readgps::Pose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::readgps::Pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0c21debd869f05bb5d743b9f76884b06";
  }

  static const char* value(const ::readgps::Pose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0c21debd869f05bbULL;
  static const uint64_t static_value2 = 0x5d743b9f76884b06ULL;
};

template<class ContainerAllocator>
struct DataType< ::readgps::Pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "readgps/Pose";
  }

  static const char* value(const ::readgps::Pose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::readgps::Pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "PointENU position\n\
Quaternion orientation\n\
Point3D linear_velocity\n\
Point3D linear_acceleration\n\
Point3D angular_velocity\n\
float64 heading\n\
Point3D linear_acceleration_vrf\n\
Point3D angular_velocity_vrf\n\
Point3D euler_angles\n\
================================================================================\n\
MSG: readgps/PointENU\n\
float64 x\n\
float64 y\n\
float64 z\n\
================================================================================\n\
MSG: readgps/Quaternion\n\
float64 qx\n\
float64 qy\n\
float64 qz\n\
float64 qw\n\
================================================================================\n\
MSG: readgps/Point3D\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::readgps::Pose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::readgps::Pose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.orientation);
      stream.next(m.linear_velocity);
      stream.next(m.linear_acceleration);
      stream.next(m.angular_velocity);
      stream.next(m.heading);
      stream.next(m.linear_acceleration_vrf);
      stream.next(m.angular_velocity_vrf);
      stream.next(m.euler_angles);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Pose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::readgps::Pose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::readgps::Pose_<ContainerAllocator>& v)
  {
    s << indent << "position: ";
    s << std::endl;
    Printer< ::readgps::PointENU_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "orientation: ";
    s << std::endl;
    Printer< ::readgps::Quaternion_<ContainerAllocator> >::stream(s, indent + "  ", v.orientation);
    s << indent << "linear_velocity: ";
    s << std::endl;
    Printer< ::readgps::Point3D_<ContainerAllocator> >::stream(s, indent + "  ", v.linear_velocity);
    s << indent << "linear_acceleration: ";
    s << std::endl;
    Printer< ::readgps::Point3D_<ContainerAllocator> >::stream(s, indent + "  ", v.linear_acceleration);
    s << indent << "angular_velocity: ";
    s << std::endl;
    Printer< ::readgps::Point3D_<ContainerAllocator> >::stream(s, indent + "  ", v.angular_velocity);
    s << indent << "heading: ";
    Printer<double>::stream(s, indent + "  ", v.heading);
    s << indent << "linear_acceleration_vrf: ";
    s << std::endl;
    Printer< ::readgps::Point3D_<ContainerAllocator> >::stream(s, indent + "  ", v.linear_acceleration_vrf);
    s << indent << "angular_velocity_vrf: ";
    s << std::endl;
    Printer< ::readgps::Point3D_<ContainerAllocator> >::stream(s, indent + "  ", v.angular_velocity_vrf);
    s << indent << "euler_angles: ";
    s << std::endl;
    Printer< ::readgps::Point3D_<ContainerAllocator> >::stream(s, indent + "  ", v.euler_angles);
  }
};

} // namespace message_operations
} // namespace ros

#endif // READGPS_MESSAGE_POSE_H
