// Generated by gencpp from file readgps/StatusPb.msg
// DO NOT EDIT!


#ifndef READGPS_MESSAGE_STATUSPB_H
#define READGPS_MESSAGE_STATUSPB_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace readgps
{
template <class ContainerAllocator>
struct StatusPb_
{
  typedef StatusPb_<ContainerAllocator> Type;

  StatusPb_()
    : error_code(0)
    , msg()  {
    }
  StatusPb_(const ContainerAllocator& _alloc)
    : error_code(0)
    , msg(_alloc)  {
  (void)_alloc;
    }



   typedef uint32_t _error_code_type;
  _error_code_type error_code;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _msg_type;
  _msg_type msg;





  typedef boost::shared_ptr< ::readgps::StatusPb_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::readgps::StatusPb_<ContainerAllocator> const> ConstPtr;

}; // struct StatusPb_

typedef ::readgps::StatusPb_<std::allocator<void> > StatusPb;

typedef boost::shared_ptr< ::readgps::StatusPb > StatusPbPtr;
typedef boost::shared_ptr< ::readgps::StatusPb const> StatusPbConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::readgps::StatusPb_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::readgps::StatusPb_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace readgps

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'readgps': ['/home/ubuwgb/catkin_ws/src/readgps/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::readgps::StatusPb_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::readgps::StatusPb_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::readgps::StatusPb_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::readgps::StatusPb_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::readgps::StatusPb_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::readgps::StatusPb_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::readgps::StatusPb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0bf0ab293456552fa4859efd5f37bafa";
  }

  static const char* value(const ::readgps::StatusPb_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0bf0ab293456552fULL;
  static const uint64_t static_value2 = 0xa4859efd5f37bafaULL;
};

template<class ContainerAllocator>
struct DataType< ::readgps::StatusPb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "readgps/StatusPb";
  }

  static const char* value(const ::readgps::StatusPb_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::readgps::StatusPb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 error_code\n\
string msg\n\
";
  }

  static const char* value(const ::readgps::StatusPb_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::readgps::StatusPb_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.error_code);
      stream.next(m.msg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StatusPb_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::readgps::StatusPb_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::readgps::StatusPb_<ContainerAllocator>& v)
  {
    s << indent << "error_code: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.error_code);
    s << indent << "msg: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.msg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // READGPS_MESSAGE_STATUSPB_H
